### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by paulocoutinhox** [mmoreram/php-formatter#37]
Hi,

What is the project status?

1 - It is abandoned?
2 - It has support for PHP 7.4?

**Comment by mmoreram** [comment]
@prsolucoes Hello!

Nopes.
The project is not abandoned.
It's simply working as expected.

For PHP7.4 support, we should take a look.
Should be just upgrade the minimum requirements in composer.json

**Comment by mmoreram** [comment]
Closing as the project works properly even with php8
